version: "3.8"

name: metasploit_by_convertor

services:
    postgres:
        networks:
            - msf
        container_name: postgres
        volumes:
            - ${HOME}/.msf4/database:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=msf
        image: postgres:11-alpine
    metasploit-framework:
        stdin_open: true
        tty: true
        networks:
            msf:
                ipv4_address: 172.18.0.3
        container_name: msf
        environment:
            - DATABASE_URL=postgres://postgres:postgres@172.18.0.2:5432/msf
        volumes:
            - ${HOME}/.msf4:/home/msf/.msf4
        ports:
            - "8443-8500:8443-8500"
        image: metasploitframework/metasploit-framework

networks:
    msf:
        ipam:
            config:
                - subnet: 172.18.0.0/16
