version: "3"
services:
    metasploitable2:
        container_name: metasploitable2
        stdin_open: true
        tty: true
        image: tleemcjr/metasploitable2:latest
        command: sh -c "/bin/services.sh && bash"
        ports:
          - "22:22"
          - "80:80"
          - "443:443"