name: dvwa
services:
  dvwa:
    image: ghcr.io/digininja/dvwa:d053c4d
    ports:
      - "4280:80"
    depends_on:
      - mysql
    environment:
      - DB_SERVER=mysql
    volumes:
      - ./config:/var/www/html/config
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: p@ssw0rd
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: